// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// sanity.cpp
int vrpr_cpp_standard();
extern "C" SEXP _vrpr_vrpr_cpp_standard() {
  BEGIN_CPP11
    return cpp11::as_sexp(vrpr_cpp_standard());
  END_CPP11
}
// sanity.cpp
bool vrpr_has_cxx20();
extern "C" SEXP _vrpr_vrpr_has_cxx20() {
  BEGIN_CPP11
    return cpp11::as_sexp(vrpr_has_cxx20());
  END_CPP11
}
// sanity.cpp
std::string vrpr_hello();
extern "C" SEXP _vrpr_vrpr_hello() {
  BEGIN_CPP11
    return cpp11::as_sexp(vrpr_hello());
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_vrpr_vrpr_cpp_standard", (DL_FUNC) &_vrpr_vrpr_cpp_standard, 0},
    {"_vrpr_vrpr_has_cxx20",    (DL_FUNC) &_vrpr_vrpr_has_cxx20,    0},
    {"_vrpr_vrpr_hello",        (DL_FUNC) &_vrpr_vrpr_hello,        0},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_vrpr(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
