# Generated by cpp11: do not edit by hand

vrpr_cpp_standard <- function() {
  .Call(`_vrpr_vrpr_cpp_standard`)
}

vrpr_has_cxx20 <- function() {
  .Call(`_vrpr_vrpr_has_cxx20`)
}

vrpr_hello <- function() {
  .Call(`_vrpr_vrpr_hello`)
}
