# Generated by cpp11: do not edit by hand

vrpr_problem_data_create <- function(depot_x, depot_y, depot_tw_early, depot_tw_late, depot_service, client_x, client_y, client_delivery, client_pickup, client_service, client_tw_early, client_tw_late, client_release, client_prize, client_required, veh_num_available, veh_capacity, veh_fixed_cost, veh_tw_early, veh_tw_late, veh_max_distance, veh_unit_distance_cost, veh_unit_duration_cost, veh_start_depot, veh_end_depot, distance, duration) {
  .Call(`_vrpr_vrpr_problem_data_create`, depot_x, depot_y, depot_tw_early, depot_tw_late, depot_service, client_x, client_y, client_delivery, client_pickup, client_service, client_tw_early, client_tw_late, client_release, client_prize, client_required, veh_num_available, veh_capacity, veh_fixed_cost, veh_tw_early, veh_tw_late, veh_max_distance, veh_unit_distance_cost, veh_unit_duration_cost, veh_start_depot, veh_end_depot, distance, duration)
}

vrpr_problem_data_summary <- function(ptr) {
  .Call(`_vrpr_vrpr_problem_data_summary`, ptr)
}

vrpr_cpp_standard <- function() {
  .Call(`_vrpr_vrpr_cpp_standard`)
}

vrpr_has_cxx20 <- function() {
  .Call(`_vrpr_vrpr_has_cxx20`)
}

vrpr_hello <- function() {
  .Call(`_vrpr_vrpr_hello`)
}
